baseURL = "https://thisisbinh.me/"
title = "Hi, this is Binh."
theme = "minimo"

Paginate = 5
preserveTaxonomyNames = true
enableRobotsTXT = true # generate robots.txt
enableEmoji = true

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
pygmentsStyle = "tango"

# Missing translations will default to this content language
defaultContentLanguage = "en"

[author]
name = "Binh Le"

[params.info]
description = "He is a Vietnamese living in Singapore, and also an SRE at Cloudflare. And this is his notes about random things he made or broke around computers."

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
#customJS = ["js/custom.js"]

[params.copyright]
prefix = ""
holder = "Binh Le"
startYear = "2018"
suffix = ""

[params.settings]
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02 — "
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
accentColor = "#FF4500"

[params.social]
email = "lebinh.it@gmail.com"
github = "lebinh"
twitter = "lebinh"
linkedin = "lebinh"

[params.social.config]
platforms = ["email","github","twitter","linkedin"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[params.widgets]
homepage = ["recent_posts"]
footer = ["social_menu"]
